---
- name: enable high power option
  hosts: windows_workstation
  gather_facts: no

  tasks: 
    - name: Change power plan to high performance
      community.windows.win_power_plan:
        name: high performance