---
#this playbook configures dhcp on a vyos router/firewall
- name: vyos
  hosts: vyos
  tasks:
    - name: load from jinja template
      template:
        src: vyos/dhcpconfig.sh.j2
        dest: /tmp/config.sh
        mode: u+rwx
    - name: run the script
      shell: nohup /tmp/config.sh &>/tmp/out.txt &